"""initial

Revision ID: ab1015cf7528
Revises: 
Create Date: 2026-03-20 03:46:22.278342
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ab1015cf7528'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumnos',
    sa.Column('cod_alumno', sa.String(length=20), nullable=False),
    sa.Column('identificacion', sa.String(length=512), nullable=False, comment='Encrypted PII'),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('grado', sa.String(length=20), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('fecha_egreso', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=512), nullable=False, comment='Encrypted PII'),
    sa.Column('telefono', sa.String(length=512), nullable=False, comment='Encrypted PII'),
    sa.Column('direccion', sa.String(length=1024), nullable=False, comment='Encrypted PII'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cod_alumno'),
    sa.UniqueConstraint('identificacion')
    )
    op.create_index('ix_alumnos_grado', 'alumnos', ['grado'], unique=False)
    op.create_index('ix_alumnos_identificacion', 'alumnos', ['identificacion'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('entidad', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.String(length=50), nullable=False),
    sa.Column('detalles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operacion', sa.String(length=100), nullable=False),
    sa.Column('detalle', sa.Text(), nullable=False),
    sa.Column('costo_estimado', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('tokens_usados', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cursos',
    sa.Column('cod_curso', sa.String(length=20), nullable=False),
    sa.Column('nombre_curso', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('grado', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cod_curso')
    )
    op.create_table('docentes',
    sa.Column('cod_docente', sa.String(length=20), nullable=False),
    sa.Column('identificacion', sa.String(length=512), nullable=False, comment='Encrypted PII'),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('fecha_ingreso', sa.Date(), nullable=False),
    sa.Column('fecha_egreso', sa.Date(), nullable=True),
    sa.Column('email', sa.String(length=512), nullable=False, comment='Encrypted PII'),
    sa.Column('telefono', sa.String(length=512), nullable=False, comment='Encrypted PII'),
    sa.Column('direccion', sa.String(length=1024), nullable=False, comment='Encrypted PII'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cod_docente'),
    sa.UniqueConstraint('identificacion')
    )
    op.create_table('materias',
    sa.Column('cod_materia', sa.String(length=20), nullable=False),
    sa.Column('nombre_materia', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cod_materia')
    )
    op.create_table('periodos_academicos',
    sa.Column('cod_periodo', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('anio', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cod_periodo')
    )
    op.create_table('plantillas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.Enum('diploma', 'certificado_notas', name='tipoplantilla'), nullable=False),
    sa.Column('idioma', sa.Enum('es', 'en', name='idiomaplantilla'), nullable=False),
    sa.Column('archivo_template_path', sa.String(length=500), nullable=False),
    sa.Column('archivo_original_path', sa.String(length=500), nullable=False),
    sa.Column('variables_mapeadas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tutores',
    sa.Column('cod_tutor', sa.String(length=20), nullable=False),
    sa.Column('identificacion', sa.String(length=512), nullable=False, comment='Encrypted PII'),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('parentesco', sa.String(length=50), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=512), nullable=False, comment='Encrypted PII'),
    sa.Column('telefono', sa.String(length=512), nullable=False, comment='Encrypted PII'),
    sa.Column('direccion', sa.String(length=1024), nullable=False, comment='Encrypted PII'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cod_tutor'),
    sa.UniqueConstraint('identificacion')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'secretaria', 'docente', name='userrole'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('alumno_tutores',
    sa.Column('cod_alumno', sa.String(length=20), nullable=False),
    sa.Column('cod_tutor', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['cod_alumno'], ['alumnos.cod_alumno'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cod_tutor'], ['tutores.cod_tutor'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cod_alumno', 'cod_tutor')
    )
    op.create_table('docente_materias',
    sa.Column('cod_docente', sa.String(length=20), nullable=False),
    sa.Column('cod_materia', sa.String(length=20), nullable=False),
    sa.Column('cod_periodo', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['cod_docente'], ['docentes.cod_docente'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cod_materia'], ['materias.cod_materia'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cod_periodo'], ['periodos_academicos.cod_periodo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cod_docente', 'cod_materia', 'cod_periodo')
    )
    op.create_table('documentos_generados',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.Enum('diploma', 'certificado_notas', name='tipodocumento'), nullable=False),
    sa.Column('cod_alumno', sa.String(length=20), nullable=False),
    sa.Column('hash_verificacion', sa.String(length=64), nullable=False, comment='SHA-256 hex'),
    sa.Column('qr_data', sa.Text(), nullable=False),
    sa.Column('archivo_path', sa.String(length=500), nullable=False),
    sa.Column('metadata_doc', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fecha_generacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cod_alumno'], ['alumnos.cod_alumno'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hash_verificacion')
    )
    op.create_index('ix_documentos_hash', 'documentos_generados', ['hash_verificacion'], unique=True)
    op.create_table('materia_grados',
    sa.Column('cod_materia', sa.String(length=20), nullable=False),
    sa.Column('grado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['cod_materia'], ['materias.cod_materia'], ),
    sa.PrimaryKeyConstraint('cod_materia', 'grado')
    )
    op.create_table('notas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cod_alumno', sa.String(length=20), nullable=False),
    sa.Column('cod_materia', sa.String(length=20), nullable=False),
    sa.Column('cod_periodo', sa.String(length=20), nullable=False),
    sa.Column('nota', sa.Numeric(precision=4, scale=2), nullable=False, comment='Grade value 0.00-10.00'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cod_alumno'], ['alumnos.cod_alumno'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cod_materia'], ['materias.cod_materia'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cod_periodo'], ['periodos_academicos.cod_periodo'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cod_alumno', 'cod_materia', 'cod_periodo', name='uq_nota_alumno_materia_periodo')
    )
    op.create_index('ix_notas_alumno_periodo', 'notas', ['cod_alumno', 'cod_periodo'], unique=False)
    op.create_index('ix_notas_materia', 'notas', ['cod_materia'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notas_materia', table_name='notas')
    op.drop_index('ix_notas_alumno_periodo', table_name='notas')
    op.drop_table('notas')
    op.drop_table('materia_grados')
    op.drop_index('ix_documentos_hash', table_name='documentos_generados')
    op.drop_table('documentos_generados')
    op.drop_table('docente_materias')
    op.drop_table('alumno_tutores')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('tutores')
    op.drop_table('plantillas')
    op.drop_table('periodos_academicos')
    op.drop_table('materias')
    op.drop_table('docentes')
    op.drop_table('cursos')
    op.drop_table('cost_log')
    op.drop_table('audit_log')
    op.drop_index('ix_alumnos_identificacion', table_name='alumnos')
    op.drop_index('ix_alumnos_grado', table_name='alumnos')
    op.drop_table('alumnos')
    # ### end Alembic commands ###
